<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Deliverable-4 Normal Flow</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-03-21T17:34:20</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>61ba2716-cfd0-4b7b-89d1-2fa201e222e6</testSuiteGuid>
   <testCaseLink>
      <guid>25c5f6e8-7655-4666-8b05-d2688940719a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Home Page/Home</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd32dfef-7f6b-49a7-a523-39a2e27681d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ce69f1e-09ec-4dc8-b18f-d0505e475ca5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b95db79-6375-46b0-a13f-35520b929e65</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a21976ee-7714-4153-8cd9-8183a8465c51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63748e2e-b202-405d-9e74-1aa62f740ba1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a374884-d6ea-4599-93f6-1f8338d71395</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>107bf60e-c6ff-47f8-a500-8ab51ea7fe16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Hello Page/Hello - Normal Flow</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f354850-f5a9-4cbb-8fff-c59aa4abb431</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dcdf6139-27af-4569-9cd8-59d3bd3da157</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Fibonacci Page/Fibonacci - Normal Flow</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b15ed59c-da41-4cf5-9771-db96fc3516dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Factorial Page/Factorial - Normal Flow</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0506bb98-e267-4d0f-835e-01fe08f3b451</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cathedral Pics/Cathedral - Normal Flow</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>912d26ba-733c-465f-87d8-5dadb7d9e1aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cathedral Pics/Cathedral - Direct</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>243f8426-ab74-455f-abb3-8bbc8b67d2ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee59e797-dfcd-4775-afc0-a0304c12c6b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Factorial Page/Factorial - Direct</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d433a2e0-aeff-4cbb-b75c-c843775b3613</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9454ee6-f3fb-48d4-aa37-e6ecf11f9142</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a29a0fec-f45d-4ff3-aa2e-f459ec665cc9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c4a1e29-7208-46cc-9599-02b564cfcd6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Fibonacci Page/Fibonacci - Direct</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83b74090-aa12-4ab4-85e4-b5e93f129a7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>625a4e7d-3f2c-40be-b518-660290f69589</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dd97b98-8254-4c2a-87dd-236dae1579c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>615c3007-314e-47ab-b841-e05217f0a907</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Hello Page/Hello - Direct</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fb4feaf-d506-4c92-a305-31df3d2d47e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9907274e-c924-420c-afa4-64f8f854e05b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
